name: trystar_aes
description: "Trystar AES"

# Build Version
version: 1.0.0+1

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  http: ^0.13.3
  shared_preferences: ^2.0.6

# App icon
flutter_launcher_icons:
  image_path_android: "assets/icons/app_icon_foreground.png"
  android: true
  adaptive_icon_background: "assets/icons/app_icon_background.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    # Add assets from the images directory to the application.
    - assets/icons/app_icon_foreground.png
  fonts:
    - family: Tradegothic
      fonts:
        - asset: assets/fonts/tradegothic/Trade_Gothic_LT.ttf
        - asset: assets/fonts/tradegothic/Trade_Gothic_LT_Bold.ttf
          style: italic
